version: "3.8"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    volumes:
      - 3x-ui-db:/etc/x-ui/
      - 3x-ui-cert:/root/cert/
    networks:
      - server
    network_mode: host
    restart: unless-stopped

volumes:
  3x-ui-db:
  3x-ui-cert:

networks:
  server:
    external: true
