version: "3.8"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    volumes:
      - 3x-ui-db:/etc/x-ui/
      - 3x-ui-cert:/root/cert/
    networks:
      - server
    network_mode: host
    restart: unless-stopped

  vpn-pihole:
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
#    ports:
#      - "53:53/tcp"
#      - "53:53/udp"
#      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
#      - "80:80/tcp"
    environment:
      TZ: 'Europe/Moscow'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - vpn-pihole:/etc/pihole
      - vpn-pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - server
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

volumes:
  3x-ui-db:
  3x-ui-cert:
  vpn-pihole:
  vpn-pihole-dnsmasq:

networks:
  server:
    external: true
