version: "3.8"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    volumes:
      - 3x-ui-db:/etc/x-ui/
      - 3x-ui-cert:/root/cert/
    networks:
      - server
    ports:
      - '30000-30050'
    restart: unless-stopped

  vpn-pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Moscow'
      DNSSEC: 'true'
    volumes:
      - vpn-pihole:/etc/pihole
      - vpn-pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - server
    restart: unless-stopped

  public-pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Moscow'
      DNSSEC: 'true'
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - public-pihole:/etc/pihole
      - public-pihole-dnsmasq:/etc/dnsmasq.d
    networks:
      - server
    restart: unless-stopped

  dnsproxy:
    image: adguard/dnsproxy
    networks:
      - server
    ports:
      - "853:853/tcp"
      - "853:853/udp"
    environment:
      - VIRTUAL_HOST=public.dns.ab.tw1.su
      - LETSENCRYPT_HOST=public.dns.ab.tw1.su
    entrypoint: sh -c "/opt/dnsproxy/dnsproxy --upstream $$(getent hosts public-pihole | awk '{ print $$1 }'):53 --tls-port=853 --tls-crt=/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/public.dns.ab.tw1.su/public.dns.ab.tw1.su.crt --tls-key=/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory/public.dns.ab.tw1.su/public.dns.ab.tw1.su.key -l 0.0.0.0"
    volumes:
      - caddy-data:/data

  caddy:
    image: ghcr.io/alexbidenko/vpn-dns-server/caddy:latest
    networks:
      - server
    volumes:
      - caddy-data:/data
      - caddy-config:/config

volumes:
  3x-ui-db:
  3x-ui-cert:
  vpn-pihole:
  vpn-pihole-dnsmasq:
  public-pihole:
  public-pihole-dnsmasq:
  caddy-data:
  caddy-config:

networks:
  server:
    external: true
