name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-caddy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./caddy.Dockerfile
          push: true
          tags: ghcr.io/alexbidenko/vpn-dns-server/caddy:latest

  deploy:
    runs-on: ubuntu-22.04

    needs: [build-caddy]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@4

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519

      - name: Deploy 🚀
        run: docker stack deploy --prune --with-registry-auth -c compose.yaml vpn-dns-server
        env:
          DOCKER_HOST: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}